services:
  node:
    container_name: node
    build: ./ValorantUnveil
    restart: always
    ports:
      - 5001:5001
    volumes:
      - postgres-volume:/var/lib/postgresql/data


  nginx:
    container_name: nginx_app
    build: .nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - postgres
      - node

  db: 
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog

volumes:
  postgres-volume: 
      
