services:
  node:
    container_name: node
    build: ./
    restart: always
    ports:
      - 5001:5001
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    depends_on:
      - db
    env_file:
      - ./.env


  nginx:
    container_name: nginx_app
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
      - node

  db: 
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog

volumes:
  postgres-volume: 
      
